### PR TITLE
Dynamic tags, searchfield & checkboxes styling.

### PR DESCRIPTION
**Pull request by MagnusTerak**
In this PR i've done the following changes

* Changed some classnames to simplify the filterbox.
* Made small adjustments in toggleTagFilter() function.
* Made small adjustments in updateDynamicTags() function.
* Created a new function handleActiveButton() to handle the "selected" state of the button-tags to simplify the styling.
* Styled the checkboxes in the filterbox.
* Styled the searchfield in the filterbox. 
* Styled the dynamic tag list in the filterbox. 

[Styling]
stylingFilterBox

### CODE REVIEW

**Review by Fagerdahl — APPROVED** [review]
Styling looks good and as expected. 
I am wondering about the missing "by rating- stars" and about some tags that I don`t see in whimsical? 

But I absolutely approve this :-) Nice work and clean code.  

Skärmbild 2024-11-27 203058

**Comment by MagnusTerak** [comment]
Working on that! Wanted to push this in a seperate PR & branch because i felt this was more of a "styling" then a new feature. But it is WIP! :)

**Review by Deansie — APPROVED** [review]
Well done Magnus! See that you changed some code regarding the dynamic tags to make it easier to style rather then the existing one, as long as the function is the same I see no issues with this whatsoever. Approved!

**Review by Fagerdahl — APPROVED** [review]

**Review by Fagerdahl — COMMENTED** [review]
👍

**Pull request merged**
