### PR TITLE
html challenges file, JS map created

### PR DESCRIPTION
**Pull request by Dusknery**
Created html challenges file and JS map. Is that good?

### CODE REVIEW

**Comment by El-Duckster** [comment]
ser bra ut!

**Comment by Fagerdahl** [comment]
Kanon! :-)

**Review by MagnusTerak — COMMENTED** [review]
Mycket bra!

**Review by Kirill9m — COMMENTED** [review]
Mycket bra!

**Comment by Deansie** [comment]
Super!

**Pull request merged**
