### PR TITLE
fix: empty stars shows only if rating is 0

### PR DESCRIPTION
**Pull request by Kirill9m**
A simple solution:

- Removes all stars after the half-star
- Adding empty stars only if the rating is below zero

I think it looks better now
If someone have more ideas I'm open.

### CODE REVIEW

**Comment by Kirill9m** [comment]
[BUG/Rating stjärnor](https://trello.com/c/NgsLWXY6/24-bug-rating-stj%C3%A4rnor)

**Comment by Deansie** [comment]
I don't believe your changes work as your hoping, I only get 1,5 stars on all challenges and when filtering from 2 stars and above the results come back empty.

**Comment by Kirill9m** [comment]
@Deansie 
Are you sure you looking at the right branch? 
I will check it soon!

> I don't believe your changes work as your hoping, I only get 2,5 stars on all challenges and when filtering from 3 stars and above the results come back empty.
> 
> Edit: My apology, I didn't realize that the any of the challenges never had rating above 2,5. However, I don't get the results you are describing:
> 
> Skärmbild från 2024-12-08 22-24-43
>

**Comment by Deansie** [comment]
> @Deansie Are you sure you looking at the right branch? I will check it soon!
> 
> > I don't believe your changes work as your hoping, I only get 2,5 stars on all challenges and when filtering from 3 stars and above the results come back empty.
> > Edit: My apology, I didn't realize that the any of the challenges never had rating above 2,5. However, I don't get the results you are describing:
> > Skärmbild från 2024-12-08 22-24-43

I feel very uncertain at this point, seeing El-ducksters post above with other results. Will look in to it later this evening, disregard my review until then.

**Comment by Kirill9m** [comment]
> good job! it seems you have fixed the bug that is connected to this branch 'empty stars shows only if rating is zero', but I think we got another issue :) the empty stars has dissappeared from the design if the rating is not zero :) image
> 
> image

@El-Duckster 

image
New solution comes:
If rating is zero , only one star is displayed.

**Pull request merged**
