### PR TITLE
Feature/display all challenges temporary card

### PR DESCRIPTION
**Pull request by El-Duckster**
### Summary
This pull request introduces functionality to display all challenges card in Challenges.html  with a temorary card solution till challenge class is ready .

###changes:
1- Fetching Challenges:
- Imported fetchAllChallenges from the API service to retrieve challenge data.
- Added error handling to gracefully display a message if challenges fail to load.

2-Rendering Challenges:
- Created a temporary TCard class (will be replaced by challengeCard) to encapsulate challenge data and generate challenge cards dynamically.

3- Interactive Booking Feature:
- Added a "Book This Challenge" button to each card.
- Implemented a handleBookButtonClick function to handle button clicks, to show the challenge ID for now (this feature will be extended in moment 3).

4- Shared State Management:

- Introduced a **shared challengesArray** to store fetched challenge data that will be used in moment 2.
- Exported a getChallengesArray function for potential external use in moment 2 

###testing
- Verified that challenges are fetched correctly and displayed with all relevant information.
-  Tested the "Book This Challenge" button functionality for proper console logging.

### Future Improvements:
-  Change the temprary card (tCard) with the actual challengeCard.
- Enhance  "Book This Challenge" button to trigger actual booking logic.

### issues
reslolves issue# 37

### CODE REVIEW

**Review by Fagerdahl — APPROVED** [review]
Du är helt otrolig Elena, allt är så snyggt ordnat och ser så bra ut.

**Review by Kirill9m — COMMENTED** [review]
Great work! 
The challenge card is almost ready, I'll soon upload the new version for review.
Overall, everything is written very well and is clear. From my side, I like everything!

If we do the merge tomorrow, I can try to integrate the class.

**Comment by Kirill9m** [comment]
Since this is a temporary solution, I hope the others won't mind if I do the merge.
I'd like to try my class on the second page so I can continue working.

Thank you for the work you've done!

**Comment by Fagerdahl** [comment]
merga på Kirill !

**Comment by Deansie** [comment]
> Helt OK att du mergade Kirill !

I concur!

**Pull request merged**
