### PR TITLE
New update for README file, suggested by Elena.

### PR DESCRIPTION
**Pull request by Kirill9m**
Screenshot_20241112_113800_Chrome

### CODE REVIEW

**Comment by El-Duckster** [comment]
super! det ser jättebra ut! tack

**Review by MagnusTerak — COMMENTED** [review]
Ser bra ut!

**Review by Deansie — COMMENTED** [review]
Ser bra ut!

**Review by Fagerdahl — APPROVED** [review]
This looks great! Nice work. I think we have a solid plan 👍

**Pull request merged**
