### PR TITLE
Enhance filtering box with tag-based filtering and improved search functionality

### PR DESCRIPTION
**Pull request by Deansie**
This PR introduces significant enhancements for the filter implementation.

These are the included changes:

1. Filtering functionality 
2. Implement debounce function for smoother search operations
3. Dynamic tag filtering
4. Display "No matching challenges" when result returns empty
5. Resetting of filtering state when filterbox is closed, showing all challenges

Testing:

1. Verified that search results render correctly in the DOM
2. Confirmed that all the functions are working properly (bugs are present)

Next steps:

1. Bug fixes for the dynamic tag filtering
2. Adding 5-Star reviews functionality @MagnusTerak 
3. Style the filter box @MagnusTerak 

Please review the changes and provide any feedback on the structure, naming conventions, or potential improvements to the search field implementation

Skärmbild från 2024-11-21 22-46-27

### CODE REVIEW

**Comment by Kirill9m** [comment]
Great work!
Well-structured code and logic easy to understand. The idea of making it case-insensitive is excellent!
I has tested the code and it doing task by displaying search results based on the text entered in the search bar.

Mu question is
On the main page in the list of three challenges there are two buttons that redirect to the full list with an active filter.
Where will the logic for this be handled, have you thought about it?

**Review by Kirill9m — APPROVED** [review]
Great work!
Well-structured code and logic easy to understand. The idea of making it case-insensitive is excellent!
I has tested the code and it doing task by displaying search results based on the text entered in the search bar.

Mu question is
On the main page in the list of three challenges there are two buttons that redirect to the full list with an active filter.
Where will the logic for this be handled, have you thought about it?

**Comment by Deansie** [comment]
> Great work! Well-structured code and logic easy to understand. The idea of making it case-insensitive is excellent! I has tested the code and it doing task by displaying search results based on the text entered in the search bar.
> 
> Mu question is On the main page in the list of three challenges there are two buttons that redirect to the full list with an active filter. Where will the logic for this be handled, have you thought about it?

Thanks for the feedback! Great question, I kind of forgot about this and will give it some thought before I decide what way to go in order to make it possible.

**Review by MagnusTerak — APPROVED** [review]
I've tried the functions on your branch and i encounter a problem when trying to filter using the tags. I am guessing this is one of the bugs you are mentioning? The other functions are working just fine! 👍 

Besides this the code looks great and im looking forward to be styling this! 💯 
Great job!

**Pull request merged**
